//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstApi.Models.Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfils
    {
        public int Id { get; set; }
        public string Compañia { get; set; }
        public string Marca { get; set; }
        public decimal Precio { get; set; }
        public int Modelo { get; set; }
        public int User { get; set; }
    
        public virtual Modeloes Modeloes { get; set; }
        public virtual Users Users { get; set; }
    }
}
